CREATE DATABASE LIBRARY
CREATE TABLE BOOK(BOOK_ID INT PRIMARY KEY, ISBN VARCHAR(10), BOOKAUTHOR VARCHAR(20), BOOKNAME VARCHAR(20), BOOKEDITION VARCHAR(20))
INSERT INTO BOOK VALUES(1, 3210,'ANWESHA','GREAT LIFE','FIRST')
INSERT INTO BOOK VALUES(2,0179,'SIDDHARTH','ROAD TO SUCCESS','FIRST')
INSERT INTO BOOK VALUES(3,0521,'ANWISID','LONG LOVE','SECOND')
INSERT INTO BOOK VALUES(4,2705,'SIDANWI','BEFOREAFTER','THIRD')
INSERT INTO BOOK VALUES(5,2021,'ANSI','COMPUTER SCIENCE','SECOND')
SELECT * FROM BOOK

CREATE TABLE BRANCH(BRANCH_ID INT PRIMARY KEY, BRANCHNAME VARCHAR(60), BRANCHLOCATION VARCHAR(60))
INSERT INTO BRANCH VALUES(1,'SEC-18 LIB','ROURKELA')
INSERT INTO BRANCH VALUES(2,'SEC-19 LIB','NOIDA')
INSERT INTO BRANCH VALUES(3,'BIHAR LIB','BIHAR')
INSERT INTO BRANCH VALUES(4,'UTKAL LIB','ODISHA')
INSERT INTO BRANCH VALUES(5,'BBSR LIB','ODISHA')
SELECT *FROM BRANCH